config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount HealthMonitor::Engine, at: "/"

  # Branded error pages
  match "/403", to: "errors#forbidden", via: :all
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :users, only: [:show]

  get "orcids/:id", to: "orcids#show", as: :orcid_show
  match "/auth/orcid/callback", to: "orcids#create", via: [:get, :post]

  get "home/index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  get "orcid_report", to: "home#orcid_report", as: :orcid_report

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
    post ":id/validate-tokens", to: "users#validate_tokens", as: :validate_tokens
  end
end

app/models/user.rb
# frozen_string_literal: true
require "devise"

class User < ApplicationRecord
  rolify
  devise :omniauthable, omniauth_providers: [:cas, :orcid]
  has_many :tokens, dependent: :destroy

  validates :uid, presence: true
  validate do |user|
    user.orcid&.strip!
    if user.orcid.present? && !ISNI.valid?(user.orcid)
      user.errors.add :base, "Invalid format for ORCID"
    end
  end

  def self.from_cas(access_token)
    user = User.find_by(uid: access_token.uid)
    # create and persist the new model
    if user.nil?
      user = User.new(uid: access_token.uid, university_id: access_token.universityid)
      user.update_with_cas(access_token)
    elsif user.provider.blank?
      user.update_with_cas(access_token)
    end
    user
  end

  # Updates an existing User record with some information from CAS.
  def update_with_cas(access_token)
    self.provider = access_token.provider
    self.email = access_token.extra.mail
    self.given_name = access_token.extra.givenname || access_token.uid # Harriet
    self.family_name = access_token.extra.sn || access_token.uid # Tubman
    self.display_name = access_token.extra.displayname || access_token.uid # "Harriet Tubman"
    self.university_id = access_token.extra.universityid # "999999999"
    save!
  end

  # Are all of this user's tokens expired?
  # returns true or false
  def tokens_expired?
    tokens.all?(&:expired?)
  end

  def valid_token
    return nil if tokens_expired?
    valid_tokens = tokens.reject(&:expired?)
    valid_tokens.first
  end

  # Revokes tokens that ORCiD reports as not valid anymore
  def revoke_invalid_tokens
    now = DateTime.now
    tokens.where("expiration > ?", now).find_each do |token|
      if Token.valid_in_orcid?(token.token, orcid) == false
        token.expiration = now
        token.save!
      end
    end
  end

  def admin?
    has_role?(:admin)
  end

  def self.create_admin(uid)
    user = User.find_or_create_by(uid:)
    user.add_role(:admin) unless user.admin?
    user
  end

  def self.create_default_users
    Rails.configuration.admins.each do |uid|
      create_admin(uid)
    end
  end

  # The following does not work for cases where ActiveRecord dynamically creates method names
  # alias_method :universityid, :university_id
  def universityid
    university_id
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def cas
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_cas(request.env["omniauth.auth"])

    if @user.nil?
      redirect_to root_path
      flash[:notice] = "You are not authorized"
    else
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      redirect_to "/orcids/#{@user.id}/show"
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: "Princeton Central Authentication Service")
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users/1 or /users/1.json
  def show
    # Is this the logged in user's own page?
    @my_page = current_user.id.to_s == @user.id.to_s
    # Unless this page belongs to the logged in user, return 403 Forbidden.
    render "errors/forbidden", status: :forbidden, formats: [:html] unless @my_page
  end

  # POST /users/1/validate-tokens
  def validate_tokens
    user = User.find(params[:id])
    user.revoke_invalid_tokens
    redirect_to user_path(user)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    # Do not allow any fishing for what database ids exist. Return 403 Forbidden.
    rescue ActiveRecord::RecordNotFound
      render "errors/forbidden", status: :forbidden, formats: [:html]
    end
end

app/helpers/users_helper.rb
# frozen_string_literal: true
module UsersHelper
  def full_orcid_display(orcid_identifier)
    return unless orcid_identifier
    full_orcid_display = ""
    full_orcid_display += "<div class='full_orcid_display'>"
    full_orcid_display += image_tag vite_asset_path("images/ORCIDiD_icon64x64.png"), alt: "ORCID icon"
    full_orcid_display += " "
    orcid_url = "https://orcid.org/#{orcid_identifier}"
    full_orcid_display += link_to orcid_url, orcid_url
    full_orcid_display += "</div>"
    full_orcid_display.html_safe
  end
end

app/views/users/_faqsection.html.erb
<div class="faq-section">
    <h2 id="faq-title">FAQs</h2>
        <div class="line-userpage" ></div>
        <div class="accordion accordion-flush">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" onfocus="log_plausible_faq('orcid')" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                        What is ORCID?
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse" aria-expanded="true">
                    <div class="accordion-body">
                        <p><a href="https://orcid.org/" target="_blank">ORCID</a> provides a unique digital persistent identifier (an ORCID iD) that you own and control throughout your scholarly career (i.e., at Princeton and elsewhere), and that distinguishes you from every other researcher. Using an ORCID iD allows your manuscripts, grants, and other scholarship to be more discoverable and integrated within larger research networks.
                        Using an ORCID iD can also help you comply with funder/sponsor requirements (particularly federal grantmaking agencies’ policies) related to both open science and research security. This is as per recent Office of Science and Technology Policy OSTP <a href="https://www.whitehouse.gov/wp-content/uploads/2022/08/08-2022-OSTP-Public-access-Memo.pdf" target="_blank">guidance</a> and National Security Presidential Memorandum 33 <a href="https://www.whitehouse.gov/wp-content/uploads/2022/01/010422-NSPM-33-Implementation-Guidance.pdf" target="_blank">(NSPM-33)</a>.</p>
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" onfocus="log_plausible_faq('no_id')" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                        What if I don’t have an ORCID iD?
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-expanded="true">
                    <div class="accordion-body">
                        <p>Anyone who participates in research, scholarship, or innovation can register an ORCID iD for themselves free of charge, and you can use the same iD throughout your whole career, even if your name changes or you move to a different organization, discipline, or country. Having an ORCID iD can help you be visible in the worldwide scholarly community, manage the data associated with your scholarly activities in one electronic repository, readily create CVs and comply with sponsors’ requirements.</p>
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" onfocus="log_plausible_faq('multi_id')" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
                        What do I do if I have more than one ORCID iD?
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-expanded="true">
                    <div class="accordion-body">
                        <p>You can quickly and easily remove your duplicate account by going to your <a href="https://orcid.org/account" target="_blank">Account Settings</a> and selecting "Remove a duplicate record". You will then be prompted to enter in the email address or ORCID iD of the duplicate account, as well as the password. 
                        When the duplicate account is removed, the email address attached to it will be added to your primary ORCID account, and all other information on the account will be deleted. 
                        For more information, please see <a href="https://support.orcid.org/hc/articles/360006896634" target="_blank">removing your additional or duplicate ORCID iD</a>.</p>
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" onfocus="log_plausible_faq('trusted_org')" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFour" aria-expanded="false" aria-controls="panelsStayOpen-collapseFour">
                        What is a “Trusted Organization”?
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseFour" class="accordion-collapse collapse" aria-expanded="true">
                    <div class="accordion-body">
                        <p>When you connect your ORCID iD to another organization’s system (e.g., a scholarly journal’s system), you will be asked to grant permission to that organization to interact with your ORCID account.
                        When you grant permission, that organization becomes a trusted organization and is listed in your <a href="https://orcid.org/trusted-parties" target="_blank">Trusted parties page</a>. See below for guidance regarding connecting your ORCID iD to Princeton.</p>
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" onfocus="log_plausible_faq('princeton_conversion')" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseFive" aria-expanded="false" aria-controls="panelsStayOpen-collapseFive">
                        Why does the University want me to connect my ORCID iD to Princeton?
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseFive" class="accordion-collapse collapse" aria-expanded="true">
                    <div class="accordion-body">
                        <p>The University would like you to link your ORCID to Princeton so that published works can be easily identified as belonging to Princeton faculty and staff. This allows the University to have more accurate and complete data pertaining to research activities.
                        Our goal is to reduce administrative burden for you! We are designing ways for you to send Princeton’s trusted data to your ORCID record to help you meet funder and publisher requirements. There are many ways to easily import trusted data into your ORCID record. Creating and/or connecting your ORCID iD to Princeton should take less than a minute.</p>
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" onfocus="log_plausible_faq('disconnect_id')" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseSix" aria-expanded="false" aria-controls="panelsStayOpen-collapseSix">
                        Can I disconnect my ORCID iD from Princeton, or from any other organization?
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseSix" class="accordion-collapse collapse" aria-expanded="true">
                    <div class="accordion-body">
                        <p>You may revoke permissions at any time. Go to the <a href="https://orcid.org/trusted-parties" target="_blank">Trusted parties page</a> and click Revoke access next to the name of the organization whose access you want to revoke. Revoking this permission means the organization will only be able to read information on your record that you have set as visible to everyone, as well as information that they themselves have added. The trusted organization will still have the ability to delete any items they have added even after the permission has been revoked but they will not be able to edit or add anything.</p>
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" onfocus="log_plausible_faq('SciENcv')" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseSeven" aria-expanded="false" aria-controls="panelsStayOpen-collapseSeven">
                        What is the relationship between ORCID and SciENcv?
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseSeven" class="accordion-collapse collapse" aria-expanded="true">
                    <div class="accordion-body">
                        <p><a href="https://www.ncbi.nlm.nih.gov/sciencv/" target="_blank">SciENcv</a> and <a href="https://orcid.org/" target="_blank">ORCID</a> are two distinct tools that can be used together to facilitate the creation of CVs and biosketches. SciENcv is a web based tool that helps researchers assemble their CVs (ideally via directly importing data from ORCID). SciENcv also produces biosketches that are in federal sponsor approved formats. Though, the CVs that SciENcv generates may be used for general purposes.
                        ORCID essentially acts as an identity management tool that provides a persistent, unique identifier and a method of linking research related products such as publications and datasets to a researcher identifier. You can transfer information from ORCID into SciENcv and use these two systems together to streamline the process of creating CVs and biosketches.</p>
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" onfocus="log_plausible_faq('cv')" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseEight" aria-expanded="false" aria-controls="panelsStayOpen-collapseEight">
                        What is the relationship between ORCID and my CV?
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseEight" class="accordion-collapse collapse" aria-expanded="true">
                    <div class="accordion-body">
                        <p>Think of your ORCID iD as a robust/authoritative repository of information about your scholarly activity. Note that you are able to toggle in ORCID which data elements you may wish to make public or keep private (or include on a CV/biosketch you produce using the data). It may be less burdensome for you to maintain your ORCID iD than different versions of your CV in various formats and for various purposes. As noted above, you may use your ORCID iD together with SciENcv to generate a CV for any purpose.</p>
                    </div>
                </div>
            </div>

            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" onfocus="log_plausible_faq('fed_agencies')" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseNine" aria-expanded="false" aria-controls="panelsStayOpen-collapseNine">
                        Are Federal Agencies requiring ORCID?
                    </button>
                </h2>
                <div id="panelsStayOpen-collapseNine" class="accordion-collapse collapse" aria-expanded="true">
                    <div class="accordion-body">
                        <p><a href="https://grants.nih.gov/grants/guide/notice-files/NOT-OD-24-163.html" target="_blank">NIH</a> and <a href="https://www.energy.gov/management/financial-assistance-letter-fal-2024-05-digital-persistent-identifier-requirements" target="_blank">DOE</a> are requiring use of ORCID iDs by researchers by May 2025. For other federal grantmaking agencies, ORCID remains optional but strongly recommended. It is expected that by May 2025, most federal agencies will require ORCID iDs on proposal submission documents and progress reports. We expect that NSF will require ORCID iDs for senior/key personnel starting in October 2025.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/_tokenprompt.html.erb
  <% token_prompt ||= "There is no ORCID iD associated with your NetID, #{current_user.uid}" %>
  <div id="minting_a_token_explanation">
  <div class="lux">
    <lux-icon-base width="30" height="30" icon-name="denied" icon-color="red">
      <lux-icon-denied></lux-icon-denied>
    </lux-icon-base>
    <span><%= token_prompt %></span>
  </div>
  <div class="orcid-connect">
    <h2>Connect your ORCID iD </h2>
    <div class="line"></div>
    <div class="info-section flex-container">
      <div>
        <p>This button will take you to ORCID to sign and and will add Princeton University as a Trusted Organization.</p>
        <p>This will allow Princeton University to read your ORCID record and add information to it.</p>
      </div>
      <%= button_to( user_orcid_omniauth_authorize_path, class: "log-in-orcid primary-button", onclick:"log_plausible_connect_orcid()") do %>
        <%= image_tag(vite_asset_path("images/ORCIDiD_icon32x32.png"), alt: "ORCID Logo") %>
        <span>Connect ORCID iD</span>
      <% end %>
    </div>
    <div class="info-section">
      <div>
        <%= link_to "Step by Step Tutorial", "https://libguides.princeton.edu/orcid-sciencv#s-lg-box-28907700", target: "_blank" %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <div class="orcid_identifier">
      <%= full_orcid_display(user.orcid) %>
    </div>
  </p>
</div>

<% if user.valid_token && orcid_available? %>
  <p>
    Your ORCID iD is connected to your NetID, <%= user.uid %>
  </p>
  <p>
    Your token grants Princeton access to read and update your ORCID record until <%= user.valid_token.expiration.strftime('%m/%d/%Y') %>.
  </p>
  <%= form_with method: :post, url: validate_tokens_path(user) do |form| %>
    <button id="check-orcid-tokens" class="btn btn-secondary"
      title="Validates that current tokens are still active with ORCiD">Check Authentication to ORCiD</button>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="relative flex min-h-screen flex-col justify-center overflow-hidden bg-gray-50 py-6 sm:py-12">

  <div class="user-page-content">
  <h1 class="page-title">ORCID@Princeton</h1>
  <div class="welcome-section">
      <% if @user.admin? %>
        <h2>Welcome, <%= @user.display_name %> (Administrator)</h2>
      <% else %>
        <h2>Welcome, <%= @user.display_name %></h2>
      <% end %>

      <!-- If the user doesn't have any tokens, prompt them to create one. -->
      <% if @user.tokens.empty? && orcid_available? %>
        <%= render 'tokenprompt' %>

      <!-- If all of the user's tokens are expired, let them know that and prompt them to create a new one -->
      <% elsif @user.tokens_expired? && orcid_available? %>
        <%= render 'tokenprompt', token_prompt: "Your ORCID token has expired. Please click the button below to re-authorize Princeton University to access your ORCID record." %>

      <!-- If the user has a valid token, show them their ORCID iD and tokens with expiration dates -->
      <% else %>
        <%= render @user %>
      <% end %>

  </div>

<%= render 'faqsection' %>

<div id="help-section-user">
  <h2 class="help-contents" id="help-title">Need help?</h2>
  <div class="help-contents" id="help-text">
    <p>If you have questions about the value of having an ORCID iD or how it will be used at Princeton, please contact the <a href="mailto:prds@princeton.edu" onclick="log_plausible_contact_us()">Princeton Research Data Service</a>.</p>
  </div>
</div>

  </div>

</div>