config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount HealthMonitor::Engine, at: "/"

  # Branded error pages
  match "/403", to: "errors#forbidden", via: :all
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :users, only: [:show]

  get "orcids/:id", to: "orcids#show", as: :orcid_show
  match "/auth/orcid/callback", to: "orcids#create", via: [:get, :post]

  get "home/index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  get "orcid_report", to: "home#orcid_report", as: :orcid_report

  devise_scope :user do
    get "sign_in", to: "devise/sessions#new", as: :new_user_session
    get "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
    post ":id/validate-tokens", to: "users#validate_tokens", as: :validate_tokens
  end
end

app/views/shared/_banner.html.erb
<% if banner_content %>
  <header id="banner" aria-label="announcement banner">
# frozen_string_literal: true
sanitize @banner_title
 %>
# frozen_string_literal: true
sanitize @banner_body
 %>
  </header>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div id="sponsors-section">
    <h2 id="sponsors-title">Project Sponsors</h2>

    <div id="sponsors-display">
      <div class="sponsors-component" id="pul-logo">
        <img src="<%= vite_asset_path('images/pul_sponsor_logo.png') %>" alt="Princeton University Library logo" />
      </div>

      <div class="sponsors-component" id="orpa-logo">
        <img src="<%= vite_asset_path('images/orpa_sponsor_logo.png') %>" alt="Princeton University Office of the Dean for Research and Project Administration logo" />
      </div>

      <div class="sponsors-component" id="prds-logo">
        <img src="<%= vite_asset_path('images/prds_sponsor_logo.png') %>" alt="Princeton Research Data Service logo" />
      </div>

      <div class="sponsors-component" id="orcid-logo">
        <img src="<%= vite_asset_path('images/orcid_sponsor_logo.png') %>" alt="ORCID: Connecting research and researchers logo" />
      </div>
    </div>
  </div>

  <div class="lux">
    <lux-library-footer></lux-library-footer>
  </div>

  <div class="p-2 text-left bg-light">
    <div class="deployment-version" >
      <text-style variation="strong">
        Version:
        <% @version = VersionFooter.info %>
        <% if @version[:stale] %>
          (stale)
        <% end %>
        <span title="<%= @version[:sha] %>">
          <% if @version[:tagged_release] %>
            <a href="https://github.com/pulibrary/orcid_princeton/releases/tag/<%= @version[:branch] %>" target="_blank"><%= @version[:branch] %></a>
          <% else %>
            <%= @version[:branch] %>,
          <% end %>
          last updated: <%= @version[:version] %>
        </span>
      </text-style>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav>
<div class="lux">
<% if current_user && current_user.admin? == true %>
    <lux-library-header app-name="ORCID@Princeton" abbr-name="ORCID@Princeton" theme="dark">
      <lux-menu-bar type="main-menu" :menu-items="[
        {name: 'Home', component: 'Home', href: '/'},
          {name: '<%= current_user.uid %>', component: 'Account', href: '/account/', children: [
            {name: 'Profile', component: 'Feedback', href: '<%= user_path(current_user )%> '},
            {name: 'ORCID Report', component: 'Feedback', href: '<%= orcid_report_path%> '},
            {name: 'Logout', component: 'Logout', href: '<%= main_app.destroy_user_session_path %> '}
          ]}
        ]"
      ></lux-menu-bar>
    </lux-library-header>
  <% elsif current_user %>
  <lux-library-header app-name="ORCID@Princeton" abbr-name="ORCID@Princeton" theme="dark">
    <lux-menu-bar type="main-menu" :menu-items="[
      {name: 'Home', component: 'Home', href: '/'},
        {name: '<%= current_user.uid %>', component: 'Account', href: '/account/', children: [
          {name: 'Profile', component: 'Feedback', href: '<%= user_path(current_user )%> '},
          {name: 'Logout', component: 'Logout', href: '<%= main_app.destroy_user_session_path %> '}
        ]}
      ]"
    ></lux-menu-bar>
  <% else %>
    <lux-library-header app-name="ORCID@Princeton" abbr-name="ORCID@Princeton" theme="dark">
    </lux-library-header>
  <% end %>
</div>
</nav>

app/views/shared/_orcid_message.html.erb
<div class="orcid-alert lux-alert lux-alert-error" role="alert">
  ORCID.org services are currently unavailable.  Contact <%= mail_to "lsupport@princeton.edu" %> for support.
</div>

app/views/shared/_plausible.html.erb
<script defer data-domain="orcid.princeton.edu" src="https://plausible.io/js/script.js"></script>

app/views/shared/_plausible_dev_staging.html.erb
<script defer data-domain="orcid-staging.princeton.edu" src="https://plausible.io/js/script.local.js"></script>

app/views/shared/_register.html.erb
<div>
You do not yet have an ORCID iD on file.

# frozen_string_literal: true
link_to "user edit page", edit_user_path(@user)
 %> and enter it.

# frozen_string_literal: true
link_to "please register with ORCID", "https://orcid.org/register"
 %> and then come back to this page.
</div>